[package]
name = "shellharden"
version = "4.1.3"
authors = ["Andreas Nordal"]
repository = "https://github.com/anordal/shellharden/"
description = "The corrective bash syntax highlighter"
license = "MPL-2.0"

[dependencies]
